spring: 
  profiles: 
    active: 
    - dev
---
server: 
  port: 8001
spring: 
  profiles: dev	#开发环境
  application:
    name: microservicecloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver             # mysql驱动包
    url: jdbc:mysql://localhost:3307/clouddb01?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false&serverTimeZone=GMT
    # 数据库名称
    username: root
    password: root
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间  

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.sjy.springcloud.pojo    # 所有Entity别名类所在包
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件 
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/

  instance:
    instance-id: dept-8001.com
    prefer-ip-address: true

info:
  app.name: sjy-microservicecloud-springcloudconfig01
  company.name: www.sjy.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
  


